/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    categories: Category;
    products: Product;
    deals: Deal;
    media: Media;
    settings: Setting;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    deals: DealsSelect<false> | DealsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  _order?: string | null;
  name: string;
  icon?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  category: number | Category;
  name: string;
  basePrice: number;
  description?: string | null;
  featuredImage?: (number | null) | Media;
  isAvailable?: boolean | null;
  isFeatured?: boolean | null;
  sizeOptions?:
    | {
        sizeName: string;
        priceModifier?: number | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  addOns?:
    | {
        name: string;
        price: number;
        maxSelection?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deals".
 */
export interface Deal {
  id: number;
  title: string;
  description?: string | null;
  products: (number | Product)[];
  featuredImage?: (number | null) | Media;
  /**
   * Automatically calculated sum of original product prices
   */
  originalTotalPrice?: number | null;
  /**
   * Special price for this bundle/deal
   */
  offerPrice: number;
  /**
   * Automatically calculated discount percentage
   */
  discountPercentage?: number | null;
  /**
   * When this deal should become active
   */
  validFrom?: string | null;
  /**
   * When this deal should expire
   */
  validUntil?: string | null;
  /**
   * Only active deals will be shown to customers
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Global settings for the app
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * Displayed in the navbar, footer, and browser tab title.
   */
  restaurantName: string;
  /**
   * Short slogan shown in the footer (e.g. "Best burgers in town!").
   */
  tagline?: string | null;
  /**
   * A brief description of your establishment (max 160 characters). Shown in the footer and can be used for SEO meta tags. Great for hospitality, food & beverage, or service businesses.
   */
  description?: string | null;
  /**
   * Navbar logo. If left empty the restaurant name text is shown instead. Recommended: transparent PNG, ~200x60 px.
   */
  logo?: (number | null) | Media;
  /**
   * Main accent color (buttons, headings, icons) in light mode.
   */
  primaryColor?: string | null;
  /**
   * Text / icon color rendered on top of the primary color in light mode.
   */
  primaryForegroundColor?: string | null;
  /**
   * Primary color in dark mode. Leave empty to reuse the light value.
   */
  primaryColorDark?: string | null;
  /**
   * Foreground color in dark mode. Leave empty to reuse the light value.
   */
  primaryForegroundColorDark?: string | null;
  /**
   * Prepended to every price on the menu (e.g. £, $, €, LBP).
   */
  currencySymbol?: string | null;
  /**
   * Toggle to hide the deals/offers section from the menu.
   */
  showDealsSection?: boolean | null;
  /**
   * Optional. Configure when your business is open. Leave "Schedule" empty to hide opening hours from the menu entirely.
   */
  openingHours?: {
    /**
     * Pick a quick preset or "Custom" to configure each day individually.
     */
    preset?: ('everyday' | 'weekdays' | 'weekends' | 'custom') | null;
    /**
     * 24-hour format, e.g. 08:30
     */
    openTime?: string | null;
    /**
     * 24-hour format, e.g. 23:00
     */
    closeTime?: string | null;
    monday?: {
      isOpen?: boolean | null;
      openTime?: string | null;
      closeTime?: string | null;
    };
    tuesday?: {
      isOpen?: boolean | null;
      openTime?: string | null;
      closeTime?: string | null;
    };
    wednesday?: {
      isOpen?: boolean | null;
      openTime?: string | null;
      closeTime?: string | null;
    };
    thursday?: {
      isOpen?: boolean | null;
      openTime?: string | null;
      closeTime?: string | null;
    };
    friday?: {
      isOpen?: boolean | null;
      openTime?: string | null;
      closeTime?: string | null;
    };
    saturday?: {
      isOpen?: boolean | null;
      openTime?: string | null;
      closeTime?: string | null;
    };
    sunday?: {
      isOpen?: boolean | null;
      openTime?: string | null;
      closeTime?: string | null;
    };
    /**
     * Short note displayed alongside hours (max 80 characters).
     */
    note?: string | null;
  };
  /**
   * International format without the + (e.g. 96178830254).
   */
  deliveryNumber: number;
  /**
   * Display name for your store location (e.g. "Main Street Branch")
   */
  locationTitle?: string | null;
  /**
   * Google Maps URL for the store (e.g. https://goo.gl/maps/...)
   */
  locationUrl?: string | null;
  /**
   * Your TikTok profile URL (e.g. https://tiktok.com/@username)
   */
  tiktokUrl?: string | null;
  /**
   * Your Facebook page URL (e.g. https://facebook.com/yourpage)
   */
  facebookUrl?: string | null;
  /**
   * Your Instagram profile URL (e.g. https://instagram.com/username)
   */
  instagramUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'deals';
        value: number | Deal;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'settings';
        value: number | Setting;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  category?: T;
  name?: T;
  basePrice?: T;
  description?: T;
  featuredImage?: T;
  isAvailable?: T;
  isFeatured?: T;
  sizeOptions?:
    | T
    | {
        sizeName?: T;
        priceModifier?: T;
        description?: T;
        id?: T;
      };
  addOns?:
    | T
    | {
        name?: T;
        price?: T;
        maxSelection?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deals_select".
 */
export interface DealsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  products?: T;
  featuredImage?: T;
  originalTotalPrice?: T;
  offerPrice?: T;
  discountPercentage?: T;
  validFrom?: T;
  validUntil?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  restaurantName?: T;
  tagline?: T;
  description?: T;
  logo?: T;
  primaryColor?: T;
  primaryForegroundColor?: T;
  primaryColorDark?: T;
  primaryForegroundColorDark?: T;
  currencySymbol?: T;
  showDealsSection?: T;
  openingHours?:
    | T
    | {
        preset?: T;
        openTime?: T;
        closeTime?: T;
        monday?:
          | T
          | {
              isOpen?: T;
              openTime?: T;
              closeTime?: T;
            };
        tuesday?:
          | T
          | {
              isOpen?: T;
              openTime?: T;
              closeTime?: T;
            };
        wednesday?:
          | T
          | {
              isOpen?: T;
              openTime?: T;
              closeTime?: T;
            };
        thursday?:
          | T
          | {
              isOpen?: T;
              openTime?: T;
              closeTime?: T;
            };
        friday?:
          | T
          | {
              isOpen?: T;
              openTime?: T;
              closeTime?: T;
            };
        saturday?:
          | T
          | {
              isOpen?: T;
              openTime?: T;
              closeTime?: T;
            };
        sunday?:
          | T
          | {
              isOpen?: T;
              openTime?: T;
              closeTime?: T;
            };
        note?: T;
      };
  deliveryNumber?: T;
  locationTitle?: T;
  locationUrl?: T;
  tiktokUrl?: T;
  facebookUrl?: T;
  instagramUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}